name: TON Docs
on:
  pull_request_target:
    types: [opened, edited, labeled, unlabeled]
permissions: read-all
jobs:
  docs-release-gate:
    uses: novusnota/test-docs/.github/workflows/docs-release-gate.yml@main
    with:
      should_error: false # that's the default
      require_same_author: true # defaults to false
      label_name: "needs-ton-docs" # that's the default
      from_branch: "test" # defaults to "*", which means any branch
      into_branch: "main" # that's the default
